ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
        files: ^(docker_podman|README.md)
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: ^(docker_podman|README.md)

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
        files: '.*\.md'